databases:
  - name: dokki
    databaseName: dokki
    user: dokki

services:
  - type: web
    name: dokki
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dokki
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
